# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [2]:
# !pip install jovian --upgrade --quiet

In [3]:
# import jovian

In [4]:
# jovian.commit(project='100-numpy-exercises')

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [5]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
print(np.show_config())

1.24.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.empty(10)

#  the values of the elements in the array may not be zero due to the uninitialized state.

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
arr1 = np.array([1,2,3,4,5])
arr1.nbytes

20

In [67]:
import sys

# Create a 2D numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the memory size of the array in bytes
size = sys.getsizeof(arr)

print(size)
# It will give the size of the array in bytes, including the memory used by the array's metadata.

164


In [68]:
# You can also use the array.itemsize attribute for finding the size of a single element in bytes and then multiply it by the total 
# number of elements in the array to find the memory size of that array.

arr.size * arr.itemsize

36

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
arr2 = np.zeros(10)
arr2[4] += 1

In [13]:
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
arr3 = np.arange(10, 50, 1)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
np.flip(arr3)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [16]:
arr3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
np.array(list(reversed(arr3)))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
np.arange(0, 9, 1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.round(np.linspace(0, 8, 9).reshape(3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [20]:
np.random.randint(0, 8, (3, 3))

array([[4, 1, 0],
       [2, 6, 2],
       [7, 3, 5]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
arr4 = np.array([1,2,0,0,4,0])
indices = np.array([])
for i in range(len(arr4)):
    if arr4[i] != 0:
        indices = np.append(indices, [i])

indices        

array([0., 1., 4.])

In [22]:
arr4 = np.array([1,2,0,0,4,0])
indices = np.array([])
for i in range(len(arr4)):
    if arr4[i] != 0:
        indices = np.concatenate((indices, [i]), axis = 0)

indices 

array([0., 1., 4.])

Save your progress by commiting your work to Jovian

In [23]:
# import jovian

In [24]:
# jovian.commit(project='numpy-100-exercises')

#### 11. Create a 3x3 identity matrix (★☆☆)

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
np.random.uniform(low = 4, high = 10, size = (3,3))

array([[4.10703845, 9.75465575, 7.09916624],
       [9.29224143, 7.00751066, 9.78426287],
       [9.98380331, 7.69615283, 5.27842431]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.uniform(low = 5, high = 15, size = (10, 10))
a

array([[10.26236394,  6.46584859, 12.39764318, 13.64499726, 14.37808803,
        14.70577714,  5.63466213, 14.05652528,  7.02038014,  9.36052316],
       [ 8.14458962, 12.99663697, 11.83805265, 10.42049841,  6.32657418,
        10.71703941, 10.84333433, 14.21728934, 14.87355924,  9.15678075],
       [11.37859365,  7.580143  , 12.17731689,  6.77825494, 14.38026358,
        10.74934992,  7.67837283,  8.57338654,  5.39849355, 13.82700888],
       [14.581764  , 11.49689694,  5.3291081 , 11.74257442, 11.76415196,
         7.3458787 , 11.76452393, 13.19208339,  9.11980182, 11.37439263],
       [ 6.40819241,  8.08282999, 11.71378346, 12.46181617, 14.90012123,
         9.31804252, 13.29757655, 10.00479737,  9.11305483,  5.93516161],
       [13.16822848,  9.21009705, 14.49436418,  9.55043554, 14.52957312,
        12.96574767, 14.30351464,  7.25464183,  8.45991687, 11.32530286],
       [ 6.67745191,  9.30455038, 10.69387665,  9.57635481,  7.44012459,
         7.63105689, 10.79280762,  9.91528029

In [28]:
a.max()

14.99219489386542

In [29]:
a.min()

5.216881263803909

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
b = np.random.uniform(1, 10, (30,))
b

array([7.75178667, 1.82364623, 7.43287477, 6.34350498, 9.73418907,
       8.00859841, 6.72614655, 8.34041487, 9.3116114 , 6.35008814,
       1.32254462, 2.77378365, 2.91744885, 2.1166961 , 6.32938278,
       9.35489873, 9.72555919, 4.52223229, 2.88396104, 3.2233516 ,
       8.8450295 , 4.11594683, 6.44115284, 8.99056372, 1.85542944,
       1.71665132, 9.50674422, 6.2225849 , 9.70383646, 9.79485854])

In [31]:
b.mean()

6.139517257137728

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
# Create an array of zeroes
arr = np.zeros((4,4))

# Create a border of ones
border = np.ones((4,4))
border[1:-1,1:-1] = 0

# Add the border to the array
result = np.pad(arr, [(1,1), (1,1)], mode='constant', constant_values=(1))

print(result)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [33]:
border = np.ones((6,6))
border[1:-1,1:-1] = 0
border

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
a = np.full((2,3),4)
a

array([[4, 4, 4],
       [4, 4, 4]])

In [35]:
rc = a.shape
rc[0]
rc[1]
zero_a = np.zeros((rc[0]+2, rc[1]+2))
zero_a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
for i in range(rc[0]):
    for j in range(rc[1]):
        zero_a[i+1][j+1] = a[i][j]
zero_a

array([[0., 0., 0., 0., 0.],
       [0., 4., 4., 4., 0.],
       [0., 4., 4., 4., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
a = np.array([[1,2,3],[4,5,6]])
rc = a.shape
rc[0]
rc[1]
zero_a = np.zeros((rc[0]+2, rc[1]+2))
for i in range(rc[0]):
    for j in range(rc[1]):
        zero_a[i+1][j+1] = a[i][j]
zero_a

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the size of the border to add
pad_width = ((3, 3), (1, 1))

# Use the numpy.pad() function to add the border
result = np.pad(arr, pad_width, 'constant')
#  the option mode = 'reflect' or 'symmetric' which will reflect the border elements rather than filling with zeroes.
result

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [62]:
0*np.nan

nan

In [69]:
np.nan == np.nan

False

In [70]:
arr = np.array([np.nan, 2, 3])
print(np.min(arr)) # nan

nan


In [71]:
np.inf > np.nan

False

In [72]:
np.inf == np.nan

False

In [73]:
np.inf < np.nan

False

In [75]:
np.nan - np.nan

nan

In [76]:
np.nan in set([np.nan])

True

In [77]:
0.3 == 3* 0.1

False

In [78]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [80]:
m_5b5 = np.eye(5)

r = m_5b5.shape
for i in range(r[0]):
    for j in range(r[1]):
        if j<i:
            m_5b5[i][j] = i
m_5b5

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [2., 2., 1., 0., 0.],
       [3., 3., 3., 1., 0.],
       [4., 4., 4., 4., 1.]])

In [82]:
# Create an identity matrix of size 5
matrix = np.eye(5)
print(matrix)
# Create an array of values to place below the main diagonal
values = np.array([1, 2, 3, 4])

# Use the diag function to place the values below the main diagonal
matrix[1:, :-1] = np.diag(values)

print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 1.]]


In [84]:
matrix1 = np.zeros((5,5))
matrix1[np.arange(1,5), np.arange(4)] = np.array([1, 2, 3, 4])
matrix1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [85]:
matrix3 = np.zeros((5,5))
matrix3[1:, :-1] = np.array([1, 2, 3, 4])
matrix3

array([[0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 0.],
       [1., 2., 3., 4., 0.],
       [1., 2., 3., 4., 0.],
       [1., 2., 3., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [90]:
chess_board = np.full((8,8), 'o')
print(chess_board)
for i in range(8):
    for j in range(8):
        if i%2 == 0:
            if j%2 == 0:
                chess_board[i][j] = 'x'
        else:
            if j%2 == 1:
                chess_board[i][j] = 'x'
chess_board

[['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']
 ['o' 'o' 'o' 'o' 'o' 'o' 'o' 'o']]


array([['x', 'o', 'x', 'o', 'x', 'o', 'x', 'o'],
       ['o', 'x', 'o', 'x', 'o', 'x', 'o', 'x'],
       ['x', 'o', 'x', 'o', 'x', 'o', 'x', 'o'],
       ['o', 'x', 'o', 'x', 'o', 'x', 'o', 'x'],
       ['x', 'o', 'x', 'o', 'x', 'o', 'x', 'o'],
       ['o', 'x', 'o', 'x', 'o', 'x', 'o', 'x'],
       ['x', 'o', 'x', 'o', 'x', 'o', 'x', 'o'],
       ['o', 'x', 'o', 'x', 'o', 'x', 'o', 'x']], dtype='<U1')

In [91]:

# Create a 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

# Fill the matrix with a checkerboard pattern
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [93]:
matrix = np.array([[(i+j)%2 for i in range(8)] for j in range(8)])
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [104]:
a1 = np.full((6,7,8), 0)
a2 = 0
for i in range(6):
    for j in range(7):
        for k in range(8):
            a2 += 1
            a1[i][j][k] = a2
            if a2 == 100:
                print('x is {}, y is {} and z is {}'.format(i,j,k))
                break

x is 1, y is 5 and z is 3


In [105]:
x,y,z = np.unravel_index(100, (6,7,8))
print('x is {}, y is {} and z is {}'.format(x,y,z))


x is 1, y is 5 and z is 4


Save your progress by commiting your work to Jovian

In [38]:
# import jovian

In [39]:
# jovian.commit()

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

Save your progress by commiting your work to Jovian

In [40]:
# import jovian

In [41]:
# jovian.commit()

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

Save your progress by commiting your work to Jovian

In [42]:
# import jovian

In [43]:
# jovian.commit()

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Save and commit your work.

In [44]:
# import jovian

In [45]:
# jovian.commit()

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

In [46]:
# import jovian

In [47]:
# jovian.commit()

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [48]:
# import jovian

In [49]:
# jovian.commit()

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [50]:
# import jovian

In [51]:
# jovian.commit()

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [52]:
# import jovian

In [53]:
# jovian.commit()

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [54]:
# import jovian

In [55]:
# jovian.commit()

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100